#!/bin/bash
Red="\005{Wr}"
Yellow="\005{Yy}"
Green="\005{Gk}"
Roster="\005{Gg}"
Blue="\005{Wb}"
Magenta="\005{Wm}"
Cyan="\005{Wc}"
White="\005{Wk}"

shorthost=$(hostname)
shorthost=${shorthost#main\.}
shorthost=${shorthost%.bluehost.com}
shorthost=${shorthost%.unifiedlayer.com}
if [[ $HOSTNAME =~ beta|smoker ]]; then
    echo -e "$Yellow[$shorthost]"
elif [[ $HOSTNAME =~ pro-ghill|sirius ]]; then
    echo -e "$White[$shorthost]"
elif [[ $HOSTNAME =~ alpha|dev ]]; then
    echo -e "$Green[$shorthost]"
elif [[ $HOSTNAME =~ jarth.org ]]; then
    echo -e "$Red[$shorthost]"
else
    echo -e "$Red[$shorthost UNKNOWN!!!]"
fi
