#!/usr/bin/perl
use warnings;
use strict;

# script dir
use FindBin;
use lib "$FindBin::Bin";

use Term::ANSIColor qw(:constants);
use CMDLine qw(package_installed);

my $RESET = RESET;
my $COLOR_SUCCESS = GREEN.BOLD;
my $COLOR_WARN    = YELLOW.BOLD;
my $COLOR_INFORM  = WHITE.BOLD;

my $logfile = "/tmp/install_ctags";
if (package_installed("ctags")) {
    inform("ctags already installed..");
    done("skipping");
}
else {
    my $home = $ENV{'HOME'};
    my $can_sudo = (`sudo -v 2>&1` !~ /may not run sudo/im);
    if (package_installed("brew")) {
        inform("installing ctags with brew\n");
        runcmd("brew install ctags >> $logfile 2>&3");
        done;

    }
    elsif ($can_sudo && package_installed("yum")) {
        inform("installing ctags with yum...");
        runcmd("sudo yum install -y ctags >> $logfile 2>&1");
        done;
    }
    else {
        chdir $home or die $!;
        inform("installing ctags in $home/bin. check $logfile for errors\n");

        #inform("downloading from sourceforge...");
        #print `curl -s -LO http://prdownloads.sourceforge.net/ctags/ctags-5.8.tar.gz`;
        #done;

        inform("cloning from github...");
        runcmd("git clone https://github.com/universal-ctags/ctags.git") unless -e "ctags";
        done;

        chdir "ctags" or die $!;
        inform("configuring source...");
        foreach my $app (qw(pkg-config automake make autoconf gcc)) {
            install_package($app) unless package_installed($app);
        }
        runcmd("./autogen.sh >> $logfile 2>&1");
        runcmd("./configure >> $logfile 2>&1");
        done;

        inform("installing...");
        runcmd("make && sudo make install >> $logfile 2>&1");
        done;

        inform("cleaning up...");
        chdir '..';
        #print `rm -rf ctags`;
        done;
    }
}
