#!/usr/bin/perl
# script dir
use FindBin;
use lib "$FindBin::Bin";

use CMDLine qw(runcmd readprompt install_package package_installed is_sudo);

# much help from https://ixnfo.com/en/mail-server-postfix-dovecot-mysql.html
# however, had to make many changes for dovecot 2.4

die "need to run as sudo" unless is_sudo;

if (!package_installed('postfix')) {
    inform("You need to install postfix manually using 'sudo apt install postfix'");
    exit;
}
my @pkgs = (
    'dovecot-core',
    'dovecot-imapd',
    'dovecot-lmtpd',
    'dovecot-mysql',
    'mariadb-server',
    'postfix-mysql',
);
for my $pkg (@pkgs) {
    install_package($pkg) unless package_installed($pkg);
}

runcmd("sudo systemctl enable mariadb.service");
runcmd("sudo systemctl start mariadb.service");
my $db_name    = $ARGV[0] || readprompt("Enter the mail database name");
my $db_user    = $ARGV[1] || readprompt("Enter the mail database user");
my $db_pass    = $ARGV[2] || readprompt("Enter the mail database password");
my $domain   = $ARGV[3] || readprompt("Enter the email hostname");
my $email      = $ARGV[4] || readprompt("Enter the email address");
my $email_pass = $ARGV[5] || readprompt("Enter the email password");

runcmd(qq{certbot certonly --apache --non-interactive --agree-tos -d '$domain'});
runcmd(qq{certbot certonly --apache --non-interactive --agree-tos -d 'mail.$domain'});
runcmd(qq{certbot certonly --apache --non-interactive --agree-tos -d 'smtp.$domain'});

runcmd(qq{echo "CREATE DATABASE IF NOT EXISTS $db_name" | sudo mysql});
runcmd(qq{echo "CREATE TABLE IF NOT EXISTS domain (domain varchar(50) NOT NULL, PRIMARY KEY (domain)) ENGINE=InnoDB DEFAULT CHARSET=utf8" | sudo mysql $db_name});
runcmd(qq{echo "CREATE TABLE IF NOT EXISTS forward (source varchar(80) NOT NULL, destination text NOT NULL, PRIMARY KEY (source)) ENGINE=InnoDB DEFAULT CHARSET=utf8" | sudo mysql $db_name});
runcmd(qq{echo "CREATE TABLE IF NOT EXISTS transport (domain varchar(128) NOT NULL DEFAULT '', transport varchar(128) NOT NULL DEFAULT '', UNIQUE KEY domain (domain)) ENGINE=InnoDB DEFAULT CHARSET=utf8" | sudo mysql $db_name});
runcmd(qq{echo "CREATE TABLE IF NOT EXISTS user (email varchar(255) NOT NULL, password varchar(255) NOT NULL, PRIMARY KEY (email)) ENGINE=InnoDB DEFAULT CHARSET=utf8" | sudo mysql $db_name});
runcmd(qq{echo "GRANT SELECT ON $db_name.* TO '$db_user'\@'127.0.0.1' IDENTIFIED BY '$db_pass'" | sudo mysql});
runcmd(qq{echo "GRANT SELECT ON $db_name.* TO '$db_user'\@'localhost' IDENTIFIED BY '$db_pass'" | sudo mysql});
runcmd(qq{echo "INSERT IGNORE INTO domain (domain) VALUES ('$domain')" | sudo mysql $db_name});
runcmd(qq{echo "INSERT IGNORE INTO user (email, password) VALUES ('$email', ENCRYPT('$email_pass', CONCAT('\$6\$', SUBSTRING(SHA(RAND()), -16))))" | sudo mysql $db_name});
runcmd(qq{echo "FLUSH PRIVILEGES" | sudo mysql});

create_and_write('/etc/postfix/main.cf', qq{
smtpd_banner = \$myhostname ESMTP \$mail_name (Ubuntu)
biff = no
# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h
readme_directory = no

# TLS parameters
smtpd_tls_chain_files=/etc/letsencrypt/live/$domain/privkey.pem, /etc/letsencrypt/live/$domain/fullchain.pem
tls_server_sni_maps = hash:/etc/postfix/ssl_map

smtpd_tls_auth_only = yes
smtp_tls_security_level = may
smtpd_tls_security_level = may
smtpd_sasl_security_options = noanonymous, noplaintext
smtpd_sasl_tls_security_options = noanonymous

# Authentication
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes

# Restrictions
smtpd_helo_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_invalid_helo_hostname,
        reject_non_fqdn_helo_hostname
smtpd_recipient_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_non_fqdn_recipient,
        reject_unknown_recipient_domain,
        reject_unlisted_recipient,
        reject_unauth_destination
smtpd_sender_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_non_fqdn_sender,
        reject_unknown_sender_domain
smtpd_relay_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        defer_unauth_destination

myhostname = $domain
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydomain = $domain
myorigin = \$mydomain
mydestination = localhost
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all

# Handing off local delivery to Dovecot's LMTP, and telling it where to store mail
virtual_transport = lmtp:unix:private/dovecot-lmtp

# Virtual domains, users, and aliases
virtual_mailbox_domains = mysql:/etc/postfix/mysql/domains.cf
virtual_mailbox_maps = mysql:/etc/postfix/mysql/mailbox_maps.cf
virtual_alias_maps = mysql:/etc/postfix/mysql/aliases.cf,
        mysql:/etc/postfix/mysql/email2email.cf

# Even more Restrictions and MTA params
disable_vrfy_command = yes
strict_rfc821_envelopes = yes
#smtpd_etrn_restrictions = reject
#smtpd_reject_unlisted_sender = yes
#smtpd_reject_unlisted_recipient = yes
smtpd_delay_reject = yes
smtpd_helo_required = yes
smtp_always_send_ehlo = yes
#smtpd_hard_error_limit = 1
smtpd_timeout = 30s
smtp_helo_timeout = 15s
smtp_rcpt_timeout = 15s
smtpd_recipient_limit = 40
minimal_backoff_time = 180s
maximal_backoff_time = 3h

# Reply Rejection Codes
invalid_hostname_reject_code = 550
non_fqdn_reject_code = 550
unknown_address_reject_code = 550
unknown_client_reject_code = 550
unknown_hostname_reject_code = 550
unverified_recipient_reject_code = 550
unverified_sender_reject_code = 550
});

create_and_write('/etc/postfix/ssl_map', qq{
$domain /etc/letsencrypt/live/$domain/privkey.pem /etc/letsencrypt/live/$domain/fullchain.pem
mail.$domain /etc/letsencrypt/live/mail.$domain/privkey.pem /etc/letsencrypt/live/mail.$domain/fullchain.pem
smtp.$domain /etc/letsencrypt/live/smtp.$domain/privkey.pem /etc/letsencrypt/live/smtp.$domain/fullchain.pem
});
runcmd("postmap -F /etc/postfix/ssl_map");

create_and_write('/etc/postfix/master.cf', q{
smtp      inet  n       -       n       -       -       smtpd

submission inet n       -       y      -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_sasl_type=dovecot
  -o smtpd_sasl_path=private/auth
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING

smtps     inet  n       -       -       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_sasl_type=dovecot
  -o smtpd_sasl_path=private/auth
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING

pickup    unix  n       -       n       60      1       pickup
cleanup   unix  n       -       n       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
#qmgr     unix  n       -       n       300     1       oqmgr
tlsmgr    unix  -       -       n       1000?   1       tlsmgr
rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       n       -       -       smtp
relay     unix  -       -       n       -       -       smtp
        -o syslog_name=${multi_instance_name?{$multi_instance_name}:{postfix}}/$service_name
#       -o smtp_helo_timeout=5 -o smtp_connect_timeout=5
showq     unix  n       -       n       -       -       showq
error     unix  -       -       n       -       -       error
retry     unix  -       -       n       -       -       error
discard   unix  -       -       n       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       n       -       -       lmtp
anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache
postlog   unix-dgram n  -       n       -       1       postlogd
});

my $basic_conf = qq{
user = $db_user
password = $db_pass
hosts = 127.0.0.1
dbname = $db_name
};

create_and_write('/etc/postfix/mysql/aliases.cf', qq{
$basic_conf
query = SELECT destination FROM forward WHERE source='%s'
});

create_and_write('/etc/postfix/mysql/domains.cf', qq{
$basic_conf
query = SELECT domain AS virtual FROM domain WHERE domain='%s'
});

create_and_write('/etc/postfix/mysql/email2email.cf', qq{
$basic_conf
query = SELECT email FROM user WHERE email='%s'
});

create_and_write('/etc/postfix/mysql/mailbox_maps.cf', qq{
$basic_conf
query = SELECT 1 FROM user WHERE email='%s'
});

runcmd("postfix check");
runcmd("systemctl restart postfix");

runcmd("mkdir -p /var/mail/vhosts/$domain");
runcmd("groupadd -f -g 5000 vmail");
runcmd("id -u vmail &>/dev/null || useradd -g vmail -u 5000 vmail -d /var/mail");
runcmd("chown -R vmail:vmail /var/mail");

create_and_write('/etc/dovecot/dovecot.conf', qq{
dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0
protocols = imap lmtp pop3
!include_try /usr/share/dovecot/protocols.d/*.protocol
!include conf.d/*.conf
!include_try local.conf
postmaster_address=postmaster\@%{user | domain}
log_debug = category=mail
});

create_and_write('/etc/dovecot/conf.d/10-mail.conf', q{
mail_driver = mbox
mail_home = /home/%{user | username}
mail_path = %{home}/mail
mail_inbox_path = /var/mail/%{user}
namespace inbox {
  inbox = yes
}
mail_privileged_group = mail
protocol !indexer-worker {
}
mail_driver = maildir
mail_path = /var/mail/vhosts/%{owner_user | domain }/%{user | username }/
});

create_and_write('/etc/dovecot/conf.d/10-auth.conf', q{
#disable_plaintext_auth = yes
auth_mechanisms = plain login
auth_username_format = %{user | username}@%{user | domain}
!include auth-system.conf.ext
!include auth-sql.conf.ext
});

create_and_write('conf.d/20-lmtp.conf', q{
protocol lmtp {
  auth_username_format = %{user | username}@%{user | domain}
}
});

create_and_write('/etc/dovecot/conf.d/auth-sql.conf.ext', qq{
sql_driver = mysql
passdb_default_password_scheme = SHA512-CRYPT
mysql /var/run/mysqld/mysqld.sock {
  user = $db_user
  password = $db_pass
  dbname = $db_name
}
passdb sql {
  query = SELECT email AS user, password FROM user WHERE email='%{user}'
}

userdb static {
  allow_all_users = yes
  fields {
    uid = vmail
    gid = vmail
    home = /var/mail/vhosts/%{user | domain}/%{user | username}
  }
}
});

runcmd("chown -R vmail:dovecot /etc/dovecot");
runcmd("chmod -R o-rwx /etc/dovecot");

create_and_write('/etc/dovecot/conf.d/10-master.conf', q{
service imap-login {
  inet_listener imap {
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service submission-login {
  inet_listener submission {
  }
  inet_listener submissions {
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

#service imap {
#}
#service submission {
#}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }

  unix_listener auth-userdb {
    mode = 0600
    user = vmail
  }
  user = dovecot
}

service auth-worker {
  user = vmail
}

service dict {
  unix_listener dict {
  }
}
});


create_and_write('/etc/dovecot/conf.d/10-ssl.conf', qq{
ssl = required
ssl_server_cert_file = /etc/dovecot/private/dovecot.pem
ssl_server_key_file = /etc/dovecot/private/dovecot.key
ssl_min_protocol = TLSv1.2
local_name smtp.$domain {
    ssl_server_cert_file = /etc/letsencrypt/live/smtp.$domain/fullchain.pem
    ssl_server_key_file  = /etc/letsencrypt/live/smtp.$domain/privkey.pem
}
local_name mail.$domain {
    ssl_server_cert_file = /etc/letsencrypt/live/mail.$domain/fullchain.pem
    ssl_server_key_file  = /etc/letsencrypt/live/mail.$domain/privkey.pem
}
local_name $domain {
    ssl_server_cert_file = /etc/letsencrypt/live/$domain/fullchain.pem
    ssl_server_key_file  = /etc/letsencrypt/live/$domain/privkey.pem
}
});

runcmd(qq{postmap -q $domain mysql:/etc/postfix/mysql/domains.cf});
runcmd(qq{postmap -q $email mysql:/etc/postfix/mysql/mailbox_maps.cf});
runcmd(q{doveconf -n});
runcmd("systemctl restart dovecot");
